# https://wiki.hypr.land/Configuring/Window-Rules/

# Master window rules
windowrule = border_size 1, rounding 1, match:class .*

# Volume Control
windowrule = tag +volume, match:initial_class ^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$
windowrule = float on, center on, size window_w window_h*0.8, pin on, match:tag volume

# Zen Browser
windowrule = workspace 2, match:class zen
windowrule = center on, float on, size monitor_w*0.8 monitor_h*0.8, match:title ^Save As.*$

# Files
windowrule = tag +files, match:initial_class ^(org.gnome.Nautilus)$
windowrule = tag +files, match:title ^(Save As.*|All Files.*|.*Files.*).*$
windowrule = float on, center on, size monitor_w*0.8 monitor_h*0.8, match:tag files

# Chrome Browser
windowrule = workspace 3, match:class google-chrome

# Slack
windowrule = workspace 4, match:class Slack

# Postman
windowrule = workspace 6, match:class Postman

# Hubstaff
windowrule = float on, center on, match:class Netsoft-com.netsoft.hubstaff

# Floating terminal
windowrule = float on, center on, size monitor_w*0.8 monitor_h*0.8, match:class floating-term
